server:
  port: 8080
  servlet:
    context-path: /unused-go
spring:
  thymeleaf:
    prefix: classpath:/static/
    suffix: .html
  datasource:
    hikari:
      jdbc-url: jdbc:postgresql://127.0.0.1:5432/ansj
      driver-class-name: org.postgresql.Driver
      username: ansj
      password: 1234
# HS512 알고리즘을 사용할 것이기 때문에 512bit, 즉 64byte 이상의 secret key를 사용해야 한다.
# Secret 값은 특정 문자열을 Base64 로 인코딩한 값 사용 (아래 명령어를 터미널에 쳐보면 그대로 나옴)
# $ echo 'spring-boot-security-jwt-tutorial-jiwoon-spring-boot-security-jwt-tutorial' | base64
jwt:
  secret: c3ByaW5nLWJvb3Qtc2VjdXJpdHktand0LXR1dG9yaWFsLWppd29vbi1zcHJpbmctYm9vdC1zZWN1cml0eS1qd3QtdHV0b3JpYWwK